import fs from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { seedDatabase, putContent, getContent, getContentById, deleteContent } from './db.js'

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const archivePath = path.join(__dirname, 'archive-data.json')
const archive = JSON.parse(fs.readFileSync(archivePath, 'utf8'))

const WORLD_CHAMPIONS = [
  ['Nino Farina','1950',1],['Juan Manuel Fangio','1951, 1954–1957',5],['Alberto Ascari','1952–1953',2],['Mike Hawthorn','1958',1],
  ['Jack Brabham','1959–1960, 1966',3],['Phil Hill','1961',1],['Graham Hill','1962, 1968',2],['Jim Clark','1963, 1965',2],['John Surtees','1964',1],['Denny Hulme','1967',1],
  ['Jackie Stewart','1969, 1971, 1973',3],['Jochen Rindt','1970',1],['Emerson Fittipaldi','1972, 1974',2],['Niki Lauda','1975, 1977, 1984',3],['James Hunt','1976',1],['Mario Andretti','1978',1],['Jody Scheckter','1979',1],
  ['Alan Jones','1980',1],['Nelson Piquet','1981, 1983, 1987',3],['Keke Rosberg','1982',1],['Alain Prost','1985–1986, 1989, 1993',4],['Ayrton Senna','1988, 1990–1991',3],
  ['Nigel Mansell','1992',1],['Michael Schumacher','1994–1995, 2000–2004',7],['Damon Hill','1996',1],['Jacques Villeneuve','1997',1],['Mika Hakkinen','1998–1999',2],['Fernando Alonso','2005–2006',2],
  ['Kimi Raikkonen','2007',1],['Lewis Hamilton','2008, 2014–2015, 2017–2020',7],['Jenson Button','2009',1],['Sebastian Vettel','2010–2013',4],['Nico Rosberg','2016',1],['Max Verstappen','2021–2024',4],['Lando Norris','2025',1]
].map(([name,years,titles],i)=>({id:`wc-${i+1}`,name,years,titles}))

const CONSTRUCTOR_CHAMPIONS = [
  ['Vanwall','1958',1],['Cooper','1959–1960',2],['Ferrari','1961, 1964, 1975, 1976, 1977, 1979, 1982–1983, 1999–2004, 2007–2008',16],
  ['BRM','1962',1],['Lotus','1963, 1965, 1968, 1970, 1972–1973, 1978',7],['Brabham','1966–1967',2],['Matra','1969',1],['Tyrrell','1971, 1973',2],
  ['McLaren','1974, 1984, 1985, 1988, 1989, 1990, 1991, 1998, 2024–2025',10],['Williams','1980–1981, 1986–1987, 1992–1994, 1996–1997',9],['Benetton','1995',1],['Renault','2005–2006',2],
  ['Brawn GP','2009',1],['Mercedes','2014–2021',8],['Red Bull Racing','2010–2013, 2022–2023',6]
].map(([name,years,titles],i)=>({id:`cc-${i+1}`,name,years,titles}))

const HISTORY = [
  {id:'1950',year:1950,title:'The first Formula 1 World Championship',summary:'The first official World Championship season begins with seven championship rounds and the Drivers’ title awarded to Nino Farina.',regulations:['The FIA Formula 1 World Championship is established.','Championship scoring and seven qualifying rounds form the original sporting framework.','Cars use a wide range of front- and rear-engined concepts under the original Formula 1 technical formula.'],beginner:'This is the starting point of the modern F1 championship.'},
  {id:'1952',year:1952,title:'Formula 2-based cars',summary:'The World Championship temporarily runs to Formula 2 technical regulations because of a shortage of suitable Formula 1 machinery.',regulations:['F2 regulations are used for the World Championship.','Engine capacity and naturally aspirated layouts are restricted under the smaller formula.'],beginner:'F1 rules changed because the championship needed enough eligible cars to form a viable grid.'},
  {id:'1958',year:1958,title:'Constructors’ Championship arrives',summary:'The second World Championship is introduced for constructors, adding a team-level title alongside the Drivers’ Championship.',regulations:['Constructors’ Championship introduced.','Fuel strategy and race distances continue to be governed by the contemporary sporting rules.'],beginner:'From this season, teams have their own championship to fight for.'},
  {id:'1961',year:1961,title:'Smaller engines and new safety emphasis',summary:'The championship adopts a 1.5-litre naturally aspirated engine formula and speed-control measures.',regulations:['Maximum engine capacity reduced to 1.5 litres for naturally aspirated engines.','Minimum car weight requirements change with the new formula.','The reduced engine formula reshapes the balance between power and chassis efficiency.'],beginner:'F1 deliberately reduces engine size to control performance and cost.'},
  {id:'1966',year:1966,title:'Three-litre engines return',summary:'Engine capacity is increased to three litres for naturally aspirated engines, opening a new power era.',regulations:['Naturally aspirated engines can run up to 3.0 litres.','2.0-litre supercharged engines are also permitted under the formula.'],beginner:'The bigger engines make power a much larger part of the competitive equation.'},
  {id:'1968',year:1968,title:'Aerodynamics becomes a weapon',summary:'Wings and aerodynamic devices rapidly become central to car performance.',regulations:['Moveable aerodynamic wings become widespread.','Wing mounting and safety requirements evolve as teams search for downforce.'],beginner:'Teams discover that controlling airflow can make a car faster without simply adding engine power.'},
  {id:'1970',year:1970,title:'Ground-effect ideas begin to emerge',summary:'Aerodynamic development moves toward managing airflow under and around the car.',regulations:['Teams increasingly explore underbody airflow and aerodynamic load generation.','Safety requirements continue to evolve around aerodynamic devices.'],beginner:'The ideas developed here eventually lead to the famous ground-effect era.'},
  {id:'1978',year:1978,title:'Ground effect becomes dominant',summary:'Lotus demonstrates how shaped sidepods and underbody tunnels can generate large amounts of efficient downforce.',regulations:['Underbody ground-effect aerodynamics become a major performance tool.','Sliding skirts are developed to seal the floor against the track.'],beginner:'Air under the car becomes almost as important as the wings on top of it.'},
  {id:'1983',year:1983,title:'Ground effect banned',summary:'Full ground-effect cars are prohibited as the rules move toward safer, more predictable aerodynamic behaviour.',regulations:['Sliding skirts are banned.','A flat-bottom requirement limits the ability to generate extreme underbody suction.'],beginner:'The FIA removes the most extreme ground-effect solutions to improve safety.'},
  {id:'1988',year:1988,title:'Turbo era reaches its final season',summary:'Turbocharged engines compete for the last time before naturally aspirated power becomes mandatory.',regulations:['Turbo engines face restrictive boost and fuel-flow rules before their 1989 ban.','Naturally aspirated alternatives remain available.'],beginner:'The sport prepares to end the turbo era after a period of extraordinary engine power.'},
  {id:'1989',year:1989,title:'Naturally aspirated engines only',summary:'Turbocharged engines are banned and the championship returns to naturally aspirated power.',regulations:['Turbocharged engines banned.','Naturally aspirated engines become the sole engine architecture.'],beginner:'This closes the first turbo era and begins a long naturally aspirated period.'},
  {id:'1994',year:1994,title:'Electronic driver aids restricted',summary:'Major electronic aids are removed as F1 responds to concerns about driver assistance and racing control.',regulations:['Active suspension, traction control and launch-control systems are prohibited at the start of the season.','Safety regulations are strengthened following the tragic 1994 Imola weekend.'],beginner:'The driver is given more direct responsibility for controlling the car.'},
  {id:'1998',year:1998,title:'Grooved tyres and narrower cars',summary:'Tyres and chassis dimensions change dramatically to reduce cornering speed.',regulations:['Grooved dry-weather tyres introduced.','Cars become narrower.','Aerodynamic rules are revised to reduce cornering performance.'],beginner:'The visible grooves in tyres are part of an attempt to reduce mechanical grip.'},
  {id:'2003',year:2003,title:'Qualifying and points system changes',summary:'Sporting regulations are adjusted to make the weekend more competitive and the championship more balanced.',regulations:['Qualifying format is changed to a single timed lap for each driver.','Points are awarded to the top eight rather than the previous top six.'],beginner:'F1 changes the weekend format and spreads points to more finishers.'},
  {id:'2009',year:2009,title:'Kinetic energy recovery and aero reset',summary:'The sport introduces KERS as a major new energy-recovery technology and dramatically simplifies aerodynamics.',regulations:['Kinetic Energy Recovery Systems (KERS) are introduced.','Front and rear wings are redesigned.','Diffusers and aerodynamic surfaces are heavily restricted.','Slick tyres return after the grooved-tyre era.'],beginner:'The car is redesigned to reduce aero complexity while recovering braking energy.'},
  {id:'2011',year:2011,title:'DRS introduced',summary:'The Drag Reduction System becomes a controlled overtaking aid.',regulations:['Adjustable rear-wing DRS introduced.','DRS use is restricted to designated activation zones during races.','KERS continues as an energy deployment system.'],beginner:'Drivers can open a rear-wing flap in a designated zone to reduce drag and improve overtaking chances.'},
  {id:'2014',year:2014,title:'Turbo-hybrid power units',summary:'F1 moves from naturally aspirated V8s to 1.6-litre V6 turbo-hybrid power units.',regulations:['1.6-litre V6 turbo hybrid power units introduced.','MGU-K recovers kinetic energy under braking.','MGU-H recovers exhaust heat energy.','Fuel-flow limits and fuel-efficiency requirements become central to performance.'],beginner:'The engine becomes a hybrid energy system rather than a conventional high-revving V8.'},
  {id:'2017',year:2017,title:'Wider, faster cars',summary:'Technical rules increase tyre width and aerodynamic load to make cars significantly faster.',regulations:['Wider front and rear tyres introduced.','Cars become wider with larger aerodynamic surfaces.','Downforce targets increase significantly.'],beginner:'F1 cars become visibly wider and faster through corners.'},
  {id:'2019',year:2019,title:'Front-wing and race-management changes',summary:'Aerodynamic rules are adjusted to make cars easier to follow and the fastest-lap point is introduced.',regulations:['Simplified front wings aim to reduce wake sensitivity.','Rear-wing and brake-duct rules are revised.','A championship point is awarded for the fastest lap when the driver finishes in the top 10.'],beginner:'The rules try to make following another car less difficult.'},
  {id:'2021',year:2021,title:'Cost cap and aero reduction',summary:'F1 introduces its first team spending cap while reducing floor and diffuser performance ahead of the 2022 reset.',regulations:['A team cost cap is introduced at a $145 million baseline.','Floor edges are cut back to reduce downforce.','Diffuser fences are shortened.','A new sliding-scale aerodynamic testing allowance is introduced.'],beginner:'Money becomes regulated as well as the cars, with lower-spending teams given a better chance to compete.'},
  {id:'2022',year:2022,title:'Ground effect returns',summary:'A major technical reset brings shaped underfloor tunnels, 18-inch wheels and a new approach to closer racing.',regulations:['Ground-effect underfloor tunnels become the main aerodynamic concept.','18-inch wheels and low-profile tyres replace 13-inch wheels.','Bargeboards are removed.','Cars are designed to produce less disruptive wake.','The power unit is frozen while teams prepare for the 2026 engine generation.'],beginner:'The floor becomes the main aerodynamic device, helping cars follow each other more closely.'},
  {id:'2026',year:2026,title:'Active aerodynamics and a new power-unit era',summary:'The biggest modern rules reset combines a lighter car, active aero and a much larger electrical contribution.',regulations:['Active front and rear aerodynamics replace the old DRS concept.','Power units target roughly a 50/50 thermal-electric power split.','MGU-H is removed and MGU-K output rises to 350 kW.','Advanced sustainable fuel becomes mandatory.','Cars are designed around a lighter, more agile concept.','New energy-management tools such as Boost and Recharge become part of race strategy.'],beginner:'The driver now manages a much larger electrical-energy strategy while the wings actively change between low-drag and high-downforce modes.'}
]

const EXTRA_GLOSSARY = [
  ['D','DRS','Drag Reduction System — the previous-generation adjustable rear-wing system used in designated zones to reduce drag and assist overtaking.'],
  ['D','Delta','A target time or speed reference that a driver must stay within during controlled-speed periods such as the Virtual Safety Car.'],
  ['E','ERS','Energy Recovery System — the hybrid system that recovers energy and stores it for later deployment.'],
  ['M','MGU-K','Motor Generator Unit-Kinetic. It recovers energy and deploys electrical power to the rear wheels; in 2026 its maximum output rises substantially.'],
  ['M','MGU-H','Motor Generator Unit-Heat. The exhaust-energy recovery unit used in the 2014–2025 hybrid era and removed for 2026.'],
  ['A','Active aerodynamics','2026 aerodynamic system that changes wing configuration to balance cornering load and straight-line efficiency.'],
  ['B','Boost','A 2026 energy-deployment concept that gives a driver extra electrical performance for attacking or defending.'],
  ['R','Recharge','A 2026 energy-management mode in which the driver and team prioritise recovering electrical energy.'],
  ['M','Manual Override Mode','A 2026 overtaking aid that gives a following car additional electrical deployment when conditions are met.'],
  ['P','Porpoising','A vertical bouncing effect caused by aerodynamic flow instability, particularly associated with ground-effect floors.'],
  ['F','Formation lap','The lap completed before the race start while drivers take their grid positions and prepare the car and tyres.'],
  ['P','Parc fermé','The controlled period during which teams are restricted from making changes to the car except those permitted by the regulations.'],
  ['S','Sprint','A shorter race held at selected Grands Prix that awards championship points and changes the weekend format.'],
  ['V','VSC','Virtual Safety Car — a digital speed-control procedure that neutralises a race without physically bunching the field behind a safety car.'],
  ['U','Underfloor','The underside of the car, including tunnels and diffuser surfaces that generate aerodynamic load.'],
  ['D','Downwash','The downward deflection of airflow produced by aerodynamic surfaces.'],
  ['C','Chicane','A sequence of alternating corners designed to slow cars and change the racing line.'],
  ['S','Slipstream','The lower-drag region behind another car that can help a following car gain speed on a straight.'],
  ['T','Tow','The aerodynamic benefit of following a car closely, especially during qualifying.'],
  ['P','Pit limiter','A system that restricts the car to the pit-lane speed limit.'],
  ['A','Allocation','The number of tyre sets or regulated power-unit or gearbox components available to a car under the sporting rules.'],
  ['A','Appeal','A formal request to review an FIA decision or sporting ruling where the regulations allow it.'],
  ['B','Brake balance','The distribution of braking force between the front and rear brakes, which the driver can adjust to change car behaviour.'],
  ['B','Brake-by-wire','An electronic braking system that works with the rear axle and energy recovery to manage braking force.'],
  ['B','Black and orange flag','A warning requiring a driver to pit because the car has damage or a mechanical problem that could be dangerous.'],
  ['C','CFD','Computational Fluid Dynamics: computer simulation used by teams to study airflow around the car.'],
  ['C','Chassis','The main structural part of the car that supports the driver, suspension and other major components.'],
  ['D','Differential','The drivetrain component that allows the driven wheels to rotate at different speeds while cornering.'],
  ['D','Diffuser','The rear section of the floor that helps manage airflow leaving beneath the car and contributes to downforce.'],
  ['D','DNQ','Did Not Qualify — a classification used when a driver does not qualify for the race under the applicable rules.'],
  ['D','DSQ','Disqualified — a driver or car has been excluded from the relevant session or classification.'],
  ['E','Esses','A sequence of left-right or right-left corners that forms an S-shaped section of track.'],
  ['K','Kerb','The raised or painted edge at the side of a circuit. Drivers may use kerbs to shorten or open a corner, but excessive use can hurt the car.'],
  ['L','Lift and coast','A fuel and energy-saving driving technique where the driver lifts off the throttle before the normal braking point and coasts into the corner.'],
  ['L','Lock-up','When a wheel stops rotating under braking and slides over the track surface, often creating a flat spot.'],
  ['M','Marbles','Small pieces of rubber shed from tyres that collect away from the main racing line and can reduce grip when driven over.'],
  ['O','Oversteer','When the rear of the car loses grip and the car turns more than the driver intended.'],
  ['O','Overtake Mode','A 2026 energy-deployment aid that replaces DRS and can provide extra electrical performance to help a following car attack.'],
  ['P','Package','A group of car upgrades designed to work together as one aerodynamic or mechanical development package.'],
  ['P','Pit board','A board shown from the pit wall to give the driver information such as position, gaps, lap count or pit instructions.'],
  ['P','Pit lane','The controlled lane alongside the circuit containing team garages and pit boxes, with a mandatory speed limit.'],
  ['P','Pit stop','A stop in the pit box, normally for tyre changes and sometimes repairs or adjustments.'],
  ['P','Pit wall','The team area beside the pit lane where strategists, engineers and senior personnel monitor the session and communicate with the driver.'],
  ['R','Race pace','The representative lap speed a driver can maintain over several laps rather than on a single qualifying-style lap.'],
  ['R','Racing line','The path through a corner that generally allows a driver to carry the best combination of entry speed, apex speed and exit speed.'],
  ['T','Track evolution','The way grip and lap times change as more rubber is laid down and track conditions change during a weekend.'],
  ['T','Tyre blanket','A heating system used before a session to bring tyres closer to their intended operating range.'],
  ['U','Unsafe release','A car being released from its pit position in a way that creates a dangerous situation for another car or person.'],
  ['U','Upgrade','A newly developed car component intended to improve performance, efficiency, reliability or aerodynamic behaviour.'],
  ['V','Visor','The transparent part of the driver’s helmet that protects the eyes while allowing the driver to see.'],
  ['Z','Zylon','A strong protective material used in parts of F1 driver and car safety equipment.'],
].map(([letter,term,definition])=>({letter,term,definition}))

seedDatabase({ archive, worldChampions: WORLD_CHAMPIONS, constructorChampions: CONSTRUCTOR_CHAMPIONS, history: HISTORY, extraGlossary: EXTRA_GLOSSARY })
for (const row of EXTRA_GLOSSARY) putContent('glossary',`${row.letter}-${row.term}`,row)


// Educational content enrichment. These fields live in SQLite too, so the Admin editor can change them.
const EDUCATIONAL = {
  flags: {
    green:{explanation:'The green flag means the track is clear and normal racing conditions have resumed.',whatToDo:'Drivers can race normally, subject to the other sporting instructions in force at that location.',why:'It tells drivers that the hazard or local restriction signalled previously has ended.',example:'After a yellow-flag zone is cleared, a green flag may be shown so drivers know they can return to normal racing speed.',watchFor:'Watch how the cars accelerate again and how the marshals change from a hazard signal back to a clear-track signal.'},
    yellow:{explanation:'A yellow flag warns that there is a hazard on or near the track. The driver must immediately reduce speed and be prepared to change direction or stop.',whatToDo:'Slow down, do not overtake where the yellow applies, and be ready for a stopped car, debris or marshals working near the circuit.',why:'Marshals need a fast visual way to warn drivers about danger before the driver reaches it.',example:'If a car stops at the outside of a corner, the next drivers may see yellow flags before reaching the incident.',watchFor:'Look for reduced speed and changes in driving behaviour through the affected sector.'},
    'double-yellow':{explanation:'Double yellow flags indicate a serious hazard. Drivers must significantly reduce speed and be prepared to stop.',whatToDo:'Reduce speed substantially, do not overtake and be ready to stop if required.',why:'The hazard is severe enough that simply lifting off is not considered sufficient protection.',example:'A recovery vehicle or badly positioned car may lead race control to use double yellows in the affected zone.',watchFor:'Cars should be visibly slower and more cautious through the zone.'},
    red:{explanation:'A red flag stops the session or race. The field must follow race-control instructions and return to the appropriate controlled area.',whatToDo:'Stop competitive running, slow safely and follow the prescribed procedure for returning to the pits or grid.',why:'Conditions may be unsafe, or race control may need to stop the session to recover a car, clear debris or address a serious incident.',example:'Heavy weather or a major accident can cause race control to suspend a session with a red flag.',watchFor:'Timing may be suspended or reset according to the applicable procedure, and the field will be managed by race control.'},
    blue:{explanation:'The blue flag is used to manage faster traffic. A lapped driver may be instructed to let a faster car through.',whatToDo:'Follow the sporting instruction and avoid unnecessarily delaying the faster car.',why:'It helps separate cars racing for position from cars that are a lap or more behind.',example:'If a leader catches a backmarker, blue flags can warn the slower car that the leader is approaching.',watchFor:'The faster car normally gains time without the lapped car fighting for track position.'},
    black:{explanation:'The black flag is a serious sporting instruction directed at a particular driver. The driver is required to return to the pits and is excluded from the relevant session or race.',whatToDo:'Return to the pits as instructed and comply with race-control procedures.',why:'It is used when race control or the stewards impose a severe sporting sanction.',example:'A driver receiving a black flag cannot simply continue racing and decide to serve it later.',watchFor:'The driver’s car number accompanies the signal so the instruction is clearly directed to that competitor.'},
    'black-white':{explanation:'The black-and-white flag is a formal warning to a driver for unsporting behaviour or a sporting infringement.',whatToDo:'Treat it as a final warning to change the behaviour and avoid another infringement.',why:'It gives race control a visible way to warn a driver before a more serious sporting penalty may follow.',example:'Repeatedly abusing track limits or another form of unsporting behaviour can lead to a black-and-white warning.',watchFor:'The driver number is normally shown with the flag so the warning is specific to that competitor.'},
    chequered:{explanation:'The chequered flag confirms that the competitive session or race has finished.',whatToDo:'Complete the lap safely and follow the post-session or parc fermé instructions.',why:'It provides the final visual signal that the competitive running is over.',example:'At the end of the Grand Prix, the first car to receive the chequered flag has completed the race distance and classification is then processed.',watchFor:'Cars slow after completing the finish procedure and teams switch from live racing decisions to post-race procedures.'}
  },
  sessions: {
    FP1:{explanation:'Free Practice 1 is the first opportunity for teams to run the car on the circuit during a normal weekend.',whatHappens:'Engineers check the baseline setup, gather aerodynamic and tyre data, test components and allow the driver to learn the track conditions.',watchFor:'Watch which tyres are used, how much fuel the teams appear to be carrying, and whether drivers make repeated runs rather than one headline lap.',whyItMatters:'The data becomes a reference for setup decisions in later sessions.',example:'A team may compare two front-wing or suspension settings to understand which gives the driver a better balance.'},
    FP2:{explanation:'Free Practice 2 is often especially valuable for long-run and race preparation because teams can study tyre behaviour over several laps.',whatHappens:'Teams combine performance runs with longer race simulations and compare tyre degradation, fuel behaviour and balance.',watchFor:'Long sequences of similar lap times are more useful for judging race pace than one qualifying-style lap.',whyItMatters:'It helps the team decide which tyre and race strategy combinations are realistic.',example:'A driver may complete ten or more laps on one compound so engineers can estimate how quickly performance falls away.'},
    FP3:{explanation:'Free Practice 3 is the final practice session and the last major chance to refine the car before qualifying.',whatHappens:'Teams focus on final setup changes, qualifying preparation and confirming that overnight adjustments have worked.',watchFor:'Look for short runs on the softer qualifying compounds and teams practising their final preparation.',whyItMatters:'Small setup decisions can affect both qualifying position and the starting point for race strategy.',example:'A team may use FP3 to decide whether it needs more front grip or a lower-drag setup.'},
    Q1:{explanation:'Q1 is the first part of qualifying. Every driver attempts to set a representative lap before the first elimination.',whatHappens:'Drivers run for lap time while teams manage traffic, tyre preparation and track evolution. The slowest group is eliminated under the qualifying format.',watchFor:'The track usually becomes faster as more rubber is laid down, so the order can change late in the session.',whyItMatters:'A poor Q1 result can put a driver at the back of the field before the race even starts.',example:'A driver who waits too long may be caught by traffic or a red flag and fail to improve.'},
    Q2:{explanation:'Q2 is the second qualifying segment for the drivers who survive Q1.',whatHappens:'Teams refine tyre preparation and timing while chasing the lap needed to reach the final segment.',watchFor:'Drivers may use different tyre choices depending on the weekend format and strategy rules.',whyItMatters:'Q2 determines which drivers get to fight for the front of the grid in Q3.',example:'A driver can gain several places simply by finding a clean final run as the track improves.'},
    Q3:{explanation:'Q3 is the final qualifying segment and the main fight for pole position.',whatHappens:'The remaining drivers make their fastest attempts, usually with maximum preparation and minimal fuel.',watchFor:'Compare the final sector splits and the gaps between teammates because tiny differences can decide pole.',whyItMatters:'The starting position strongly influences the first-lap and race strategy options.',example:'Two drivers can be separated by only a few hundredths of a second even though both have produced excellent laps.'},
    SPRINT:{explanation:'The Sprint is a shorter competitive race used at selected Grand Prix weekends and follows a different weekend schedule from a standard event.',whatHappens:'Drivers race over a shorter distance while managing tyres, overtaking opportunities and championship points.',watchFor:'Because the race is shorter, teams may accept more aggressive tyre and energy decisions.',whyItMatters:'It awards championship points and can affect the way teams approach the rest of the weekend.',example:'A driver may attack more aggressively because there are fewer laps in which to recover lost positions.'},
    RACE:{explanation:'The Grand Prix is the main championship race and the session in which the bulk of the race weekend’s championship points are normally scored.',whatHappens:'Drivers manage pace, tyres, fuel and energy while teams make pit-stop and safety-car decisions.',watchFor:'Follow the tyre ages, pit windows, gaps, safety-car periods and the difference between qualifying pace and long-run pace.',whyItMatters:'The race determines the official finishing order and contributes to both championships.',example:'A driver can start behind a rival but finish ahead through better tyre management and a well-timed pit stop.'}
  },
  rules: {
    Championship:{explanation:'Formula 1 has two main championship classifications: the Drivers’ Championship and the Constructors’ Championship.',howItWorks:'Drivers score points from eligible race and sprint results. Constructor points are the points scored by the team’s eligible drivers, subject to the regulations and classification.',example:'Two teammates can both score points for the same constructor even while fighting each other for the Drivers’ Championship.',whyItMatters:'It explains why one driver can win the Drivers’ title while a different team wins the Constructors’ title.',beginnerTip:'Think of the Drivers’ Championship as the individual competition and the Constructors’ Championship as the team competition.'},
    Grid:{explanation:'The starting grid is the ordered list of cars at the beginning of a race or Sprint.',howItWorks:'Qualifying establishes the starting order, but penalties, non-participation and official decisions can change a driver’s final grid position.',example:'A driver who qualifies third but receives a grid penalty may start lower than third.',whyItMatters:'Starting position changes the amount of clean air, traffic and overtaking a driver is likely to face.',beginnerTip:'Qualifying position and actual starting position are not always the same.'},
    'Pit Lane':{explanation:'The pit lane is a controlled section where cars enter for pit stops and access to team garages.',howItWorks:'Cars must respect the pit-lane speed limit and obey entry, exit and race-control procedures.',example:'A driver speeding in the pit lane can receive a penalty even if they gain no track position.',whyItMatters:'The pit lane is a high-risk working area with mechanics, equipment and cars moving in a confined space.',beginnerTip:'A pit stop is not simply stopping; the driver must enter and exit the pit lane correctly.'},
    Tyres:{explanation:'Tyre regulations define which compounds and tyre sets drivers can use and how teams may manage them during a weekend.',howItWorks:'Teams choose from the compounds allocated for the event and plan when each set will be used.',example:'A team may save a new soft set for qualifying rather than using it early in practice.',whyItMatters:'Tyres often determine whether a car can maintain pace for a long stint.',beginnerTip:'Think about tyres as a performance resource: grip now versus life later.'},
    'Safety Car':{explanation:'The Safety Car is a physical car that leads the field when the race cannot continue at normal speed but a complete stop is not necessary.',howItWorks:'Cars form a controlled queue behind the Safety Car while race control manages the incident and the track.',example:'A crash may trigger a Safety Car period so marshals can work without cars racing past at full speed.',whyItMatters:'A Safety Car can dramatically change gaps and make pit stops strategically cheaper.',beginnerTip:'Watch how the field bunches together — that is why a Safety Car can erase a large lead.'},
    'Virtual Safety Car':{explanation:'The Virtual Safety Car controls car speeds without using a physical Safety Car to bunch the field together.',howItWorks:'Drivers must stay within a prescribed speed-time delta while continuing around the circuit.',example:'A stranded car can trigger VSC while marshals recover it, reducing the speed of every driver through the affected period.',whyItMatters:'It improves safety while preserving more of the existing gaps than a physical Safety Car.',beginnerTip:'VSC means controlled speed; Safety Car means controlled speed plus a physical car leading the field.'},
    Penalties:{explanation:'Penalties are sporting sanctions applied when drivers or teams breach the regulations.',howItWorks:'Stewards investigate incidents using timing, video, radio and other evidence before deciding the appropriate sanction.',example:'Depending on the infringement, a driver could receive a time penalty or a grid penalty.',whyItMatters:'Penalties ensure that gaining an advantage by breaking the rules is not treated as normal racing.',beginnerTip:'An investigation does not automatically mean a penalty; the stewards must establish whether a breach occurred.'},
    'Track Limits':{explanation:'Track limits define where the racing surface ends. Drivers cannot repeatedly or deliberately gain an advantage by exceeding them.',howItWorks:'Timing systems, cameras and other evidence can be used to detect infringements. Consequences depend on the applicable sporting rules.',example:'A lap can be deleted in qualifying if a driver exceeds the track limits at a monitored corner.',whyItMatters:'Track limits stop drivers from using extra asphalt or run-off as a free shortcut.',beginnerTip:'A fast lap is only useful if it is legal.'}
  },
  strategies: {
    undercut:{explanation:'The undercut means stopping before a rival and using fresh tyres to set faster laps while the rival remains on older tyres.',tradeoff:'It can gain track position but may expose the driver to traffic, a slow warm-up lap or a Safety Car that arrives at the wrong time.',example:'If a driver is stuck behind a rival, the team may pit one lap earlier and hope the fresh-tyre pace creates enough time to emerge ahead after the rival stops.'},
    overcut:{explanation:'The overcut means staying out after a rival pits and using the extra laps to build a time advantage before making your own stop.',tradeoff:'It only works if the old tyres retain enough pace and the rival does not gain too much on fresh rubber.',example:'On a cool track where new tyres are difficult to warm up, staying out can sometimes be faster than stopping immediately.'},
    'go-long':{explanation:'Going long means extending a stint instead of responding immediately to a rival’s pit stop.',tradeoff:'The driver sacrifices immediate track position in exchange for fresher tyres later.',example:'A driver may stay out during a Safety Car threat or when overtaking is difficult, hoping a late stop gives them a strong final stint.'},
    'one-stop':{explanation:'A one-stop race plan uses one scheduled tyre change and therefore spends less time in the pit lane.',tradeoff:'The driver must make the tyres last, so the car may be slower at the end of a long stint.',example:'A durable compound can be used for a long middle stint while the driver protects it to avoid a second stop.'},
    'two-stop':{explanation:'A two-stop plan trades an additional pit-lane visit for more time on faster, fresher tyres.',tradeoff:'The extra stop costs track position and pit-lane time, but can recover more lap time through lower tyre degradation.',example:'If the tyres fall away quickly, two shorter stints can be faster overall than stretching one set too far.'},
    'safety-car':{explanation:'A Safety Car window is an opportunity to pit while the field is running slower, reducing the relative time cost of the stop.',tradeoff:'The team cannot control exactly when the Safety Car appears or how long it lasts.',example:'A driver with a tyre change due soon may gain a major strategic advantage if a Safety Car appears at exactly the right moment.'}
  },
  tyres: {
    hard:{explanation:'The hard slick is designed to offer long stint life and stable performance at the cost of lower peak grip compared with softer compounds.',conditions:'Useful when degradation is high, the track is hot or a team needs a long stint.',driverFeel:'The driver normally gets a more durable but less immediately responsive tyre compared with a soft compound.',example:'A hard tyre can be valuable for the middle or final stint when the team needs to reach the finish without another stop.',strategyNote:'Hard tyres can make a one-stop strategy easier, but their warm-up and peak pace must be considered.'},
    medium:{explanation:'The medium slick sits between the hard and soft in expected grip and life and is often the most flexible strategic option.',conditions:'Useful when a team wants a compromise between race pace and tyre life.',driverFeel:'It generally offers a predictable balance of grip and durability.',example:'A team may use the medium for a middle stint because it gives enough pace without the short life of the soft.',strategyNote:'The medium is often valuable because it leaves several strategy options open.'},
    soft:{explanation:'The soft slick provides the highest peak grip of the selected dry compounds but normally has shorter life.',conditions:'Useful for qualifying, short aggressive stints and situations where immediate lap time matters most.',driverFeel:'It can feel responsive and grippy when inside its operating window, but performance can fall away more quickly.',example:'A driver may use a new soft tyre for the final qualifying attempt to maximise one-lap performance.',strategyNote:'Soft tyres are not automatically the fastest race choice because degradation and pit-stop cost matter.'},
    intermediate:{explanation:'The intermediate is the green wet-weather tyre for conditions where slicks no longer provide enough grip but the track is not wet enough to require full wets.',conditions:'Useful in light or mixed rain and on a drying or damp circuit.',driverFeel:'It provides extra water displacement and more confidence than a slick in damp conditions.',example:'If rain starts during a race and the track becomes too wet for slicks, a team may switch to intermediates.',strategyNote:'The crossover point between slicks and intermediates is a major strategic decision because a tyre can quickly become too hot or too cold for the conditions.'},
    wet:{explanation:'The full wet is designed to move substantially more water than an intermediate in heavy rain and standing-water conditions.',conditions:'Used when water levels are too high for intermediates to work safely and effectively.',driverFeel:'The car gains greater water-displacement capability, although lap speed is lower in the heavy-rain conditions where it is needed.',example:'In a heavily flooded section of track, full wets can reduce aquaplaning risk compared with a less capable tyre.',strategyNote:'Visibility and standing water can still make conditions too dangerous for racing even when a wet-weather tyre is available.'}
  }
}
for (const [id,detail] of Object.entries(EDUCATIONAL.flags)) { const row=getContentById('flags',id); if(row) putContent('flags',id,{...row,...detail}) }
for (const [id,detail] of Object.entries(EDUCATIONAL.sessions)) { const row=getContentById('sessions',id); if(row) putContent('sessions',id,{...row,...detail}) }
for (const [id,detail] of Object.entries(EDUCATIONAL.rules)) { const row=getContentById('rules',id); if(row) putContent('rules',id,{...row,...detail}) }
for (const [id,detail] of Object.entries(EDUCATIONAL.strategies)) { const row=getContentById('strategies',id); if(row) putContent('strategies',id,{...row,...detail}) }
for (const [id,detail] of Object.entries(EDUCATIONAL.tyres)) { const row=getContentById('tyres',id); if(row) putContent('tyres',id,{...row,...detail}) }
const glossaryRows=getContent('glossary')
for (const row of glossaryRows) {
  const term=String(row.term||'')
  const extra={
    explanation:row.definition,
    raceUse:`${term} can appear in team radio, timing analysis, technical discussions or race commentary depending on the situation.`,
    example:`For a beginner, the easiest way to recognise ${term} is to connect it with the part of F1 it changes — car balance, grip, speed, energy, tyres, strategy or the rules.`,
    whyItMatters:`Knowing ${term} helps you understand why a driver, engineer or commentator describes a particular problem or decision.`,
    beginnerTip:'When you hear this term, ask what it changes on the car or in the race. That single question usually reveals its meaning.'
  }
  putContent('glossary',`${row.letter}-${row.term}`,{...row,...extra})
}
// Upgrade a set of high-value terms with concrete beginner examples.
const glossaryExamples={
  'Active aerodynamics':{explanation:'The 2026 car uses moveable aerodynamic elements at the front and rear. They can change between configurations that prioritise cornering load and straight-line efficiency.',example:'Think of it as the car changing its aerodynamic shape for different parts of a lap: more load in corners and less drag on suitable straights.',whyItMatters:'It is one of the most visible changes in the 2026 technical rules and replaces the old DRS concept.',beginnerTip:'Active aero is about changing the car’s aerodynamic balance while it is running, not simply adding a fixed wing.'},
  DRS:{explanation:'DRS was the Drag Reduction System used before 2026. It opened a rear-wing flap in specified conditions to reduce drag and help a following car attack.',example:'A driver close enough to a rival could use DRS on an eligible straight and gain extra speed.',whyItMatters:'DRS is important for understanding older races and the history behind the 2026 overtaking system.',beginnerTip:'In 2026, learn DRS as the previous system; the new rules use active aero and Overtake Mode.'},
  'Overtake Mode':{explanation:'Overtake Mode is a new-for-2026 energy deployment aid designed to help a following car attack. It replaces DRS as the main straight-line overtaking aid.',example:'A driver within the required gap at the detection point can use the additional electrical performance on the following lap.',whyItMatters:'It changes overtaking from a simple wing-opening action into an energy-management decision.',beginnerTip:'Remember: active aero manages aerodynamic drag and downforce; Overtake Mode manages electrical performance for an attack.'},
  'Lift and coast':{explanation:'The driver lifts off the throttle before the normal braking point and coasts for part of the approach to a corner.',example:'If an engineer says “lift and coast for three corners”, the driver deliberately gives up a little lap time to save fuel or recover energy.',whyItMatters:'It shows that F1 drivers are managing more than tyre grip — they also manage fuel and electrical energy.',beginnerTip:'Lift and coast = lift earlier, coast longer, save resources.'}
}
for (const row of getContent('glossary')) { const e=glossaryExamples[row.term]; if(e) putContent('glossary',`${row.letter}-${row.term}`,{...row,...e}) }


const HISTORY_EDU={
1950:{why:'The championship needed a common international framework so major Grand Prix competition could be recognised as one world title.',impact:'It created the sporting foundation from which the modern championship evolved.',example:'Nino Farina became the first Drivers’ World Champion.'},
1952:{why:'There were not enough suitable Formula 1 cars to maintain a viable championship grid.',impact:'Using Formula 2 regulations kept the championship running while the sport adapted.',example:'Smaller-engined cars competed for the World Championship in 1952 and 1953.'},
1958:{why:'The sport needed to recognise the manufacturers and teams whose cars competed as well as the individual drivers.',impact:'The Constructors’ Championship created a permanent team-level competition.',example:'Vanwall became the first Constructors’ World Champion.'},
1961:{why:'Engine performance and speeds were increasing, so the technical formula was reset.',impact:'The 1.5-litre formula changed the balance between engine power, chassis efficiency and reliability.',example:'Teams had to find performance without relying on large-displacement engines.'},
1966:{why:'The previous 1.5-litre formula had run its course and the sport wanted a new power ceiling.',impact:'The return to larger engines opened another major engine-development era.',example:'Naturally aspirated engines up to three litres became eligible.'},
1968:{why:'Teams discovered that airflow could generate performance without adding engine power.',impact:'Aerodynamic development became a central engineering discipline in F1.',example:'Wings began appearing in increasingly sophisticated forms on F1 cars.'},
1970:{why:'Teams were looking for more efficient ways to generate downforce.',impact:'Underbody airflow became a major area of experimentation and eventually led to full ground-effect cars.',example:'Lotus and other teams developed ideas that treated the floor as an aerodynamic device.'},
1978:{why:'Ground-effect tunnels could create large amounts of downforce with less drag than simply making the wings larger.',impact:'The technique transformed cornering performance but also created new safety and stability challenges.',example:'Lotus demonstrated the effectiveness of shaped sidepods and underbody tunnels.'},
1983:{why:'The FIA wanted to reduce the extreme aerodynamic loads and unpredictable behaviour associated with sliding-skirt ground-effect cars.',impact:'Flat-bottom rules changed how teams generated downforce and pushed development back toward wings and diffusers.',example:'Teams could no longer seal the floor to the track with sliding skirts.'},
1988:{why:'Turbo engines had become extremely powerful, and the rules were preparing for their removal.',impact:'The final turbo season became a technical transition point between turbocharged and naturally aspirated eras.',example:'Turbo restrictions limited boost and fuel use before the 1989 ban.'},
1989:{why:'The turbo formula had become too expensive and difficult to control.',impact:'Naturally aspirated engines became the sole engine architecture.',example:'Teams switched their focus to high-revving naturally aspirated designs.'},
1994:{why:'F1 wanted the driver to have more direct control rather than relying on electronic assistance.',impact:'Electronic driver aids were removed while safety requirements also became a major focus after the events at Imola.',example:'Active suspension, traction control and launch-control systems were prohibited at the start of the season.'},
1998:{why:'The FIA wanted to reduce cornering performance and change the mechanical-grip balance.',impact:'Grooved tyres and narrower cars altered how drivers generated grip and how teams designed their suspension and aerodynamics.',example:'Dry-weather tyres visibly gained grooves instead of using a fully slick surface.'},
2003:{why:'The sporting format was repeatedly adjusted to make qualifying and the points battle more engaging.',impact:'The single-lap qualifying format changed the risk-reward balance and the points expansion rewarded more finishers.',example:'More drivers could score championship points than under the earlier top-six system.'},
2009:{why:'F1 wanted to reduce aerodynamic complexity and introduce new energy-recovery technology.',impact:'KERS brought hybrid energy recovery into the sport while slick tyres and revised wings changed mechanical and aerodynamic balance.',example:'Drivers could deploy recovered braking energy for extra performance.'},
2011:{why:'Overtaking was difficult in disturbed air, so F1 introduced a controlled aerodynamic aid.',impact:'DRS became a defining part of race strategy for more than a decade.',example:'A driver within the required gap at a detection point could open the rear-wing flap in a DRS zone.'},
2014:{why:'F1 moved toward greater efficiency and a more sophisticated hybrid power system.',impact:'The 1.6-litre V6 turbo-hybrid era made energy recovery, fuel flow and thermal efficiency central to performance.',example:'The MGU-K recovered braking energy while the MGU-H recovered exhaust energy.'},
2017:{why:'F1 wanted cars that were faster and more visually aggressive.',impact:'Wider tyres and larger aerodynamic surfaces increased cornering speeds and changed tyre management.',example:'Cars became wider and carried larger tyres compared with the previous generation.'},
2019:{why:'F1 adjusted the front wing and other race-management elements to improve following and simplify some aerodynamic behaviour.',impact:'The front wing became a larger part of how teams managed the car’s airflow and balance.',example:'Teams had to redesign their aerodynamic philosophy around the new front-wing regulations.'},
2021:{why:'F1 introduced financial controls while also reducing some aerodynamic load to protect tyre performance and improve close racing.',impact:'The cost cap changed how teams planned development and spending.',example:'Teams had to make trade-offs about which upgrades were worth their limited development budget.'},
2022:{why:'The FIA wanted cars that could follow each other more closely by reducing the negative effect of turbulent air.',impact:'Ground-effect floors returned and the aerodynamic philosophy changed dramatically.',example:'Venturi-style tunnels under the floor generated much of the car’s downforce.'},
2026:{why:'F1 redesigned the cars around closer racing, greater electrical power, efficiency and a new aerodynamic philosophy.',impact:'Active front and rear aerodynamic elements, a new power-unit balance, sustainable fuel and new energy-management concepts reshape the cars.',example:'Active aero can switch between configurations that prioritise cornering load and straight-line efficiency, while Overtake Mode replaces the old DRS concept.'}
}
for(const row of getContent('history')){const e=HISTORY_EDU[Number(row.year)];if(e)putContent('history',row.id,{...row,...e})}

// Patch current-season values and packaged career stats used as the initial database seed as of the latest completed 2026 round in the source used for this build.
const verified = {
  'george-russell': {wins:7,podiums:29,poles:12,careerPoints:1193,grandsPrix:163,dnfs:21,championships:0,season:{position:3,points:160,grandPrixPoints:134,wins:2,podiums:5,poles:4,fastestLaps:0,dnfs:2}},
  'kimi-antonelli': {wins:6,podiums:12,poles:6,careerPoints:369,grandsPrix:35,dnfs:5,championships:0,season:{position:1,points:219,grandPrixPoints:198,wins:6,podiums:9,poles:6,fastestLaps:0,dnfs:1}},
  'charles-leclerc': {wins:9,podiums:54,poles:27,careerPoints:1810,grandsPrix:182,dnfs:25,championships:0,season:{position:4,points:138,grandPrixPoints:117,wins:1,podiums:4,poles:0,fastestLaps:1,dnfs:0}},
  'lewis-hamilton': {wins:106,podiums:207,poles:104,careerPoints:5187.5,grandsPrix:391,dnfs:34,championships:7,season:{position:2,points:169,grandPrixPoints:151,wins:1,podiums:5,poles:0,fastestLaps:1,dnfs:0}},
  'lando-norris': {wins:12,podiums:47,poles:17,careerPoints:1558,grandsPrix:162,dnfs:17,championships:1,season:{position:5,points:128,grandPrixPoints:102,wins:1,podiums:3,poles:1,fastestLaps:2,dnfs:2}},
  'oscar-piastri': {wins:9,podiums:28,poles:6,careerPoints:891,grandsPrix:79,dnfs:7,championships:0,season:{position:7,points:92,grandPrixPoints:75,wins:0,podiums:2,poles:0,fastestLaps:0,dnfs:1}},
  'max-verstappen': {wins:71,podiums:131,poles:48,careerPoints:3553.5,grandsPrix:244,dnfs:36,championships:4,season:{position:6,points:109,grandPrixPoints:100,wins:0,podiums:4,poles:0,fastestLaps:1,dnfs:3}},
  'isack-hadjar': {wins:1,podiums:1,poles:0,careerPoints:119,grandsPrix:34,dnfs:4,championships:0,season:{position:8,points:68,grandPrixPoints:68,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:2}},
  'liam-lawson': {wins:0,podiums:0,poles:0,careerPoints:87,grandsPrix:46,dnfs:8,championships:0,season:{position:9,points:43,grandPrixPoints:40,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:1}},
  'arvid-lindblad': {wins:0,podiums:0,poles:0,careerPoints:23,grandsPrix:10,dnfs:1,championships:0,season:{position:11,points:23,grandPrixPoints:22,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:0}},
  'pierre-gasly': {wins:1,podiums:6,poles:0,careerPoints:500,grandsPrix:188,dnfs:29,championships:0,season:{position:10,points:42,grandPrixPoints:41,wins:0,podiums:1,poles:0,fastestLaps:0,dnfs:1}},
  'franco-colapinto': {wins:0,podiums:0,poles:0,careerPoints:24,grandsPrix:37,dnfs:4,championships:0,season:{position:12,points:19,grandPrixPoints:19,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:0}},
  'esteban-ocon': {wins:1,podiums:4,poles:0,careerPoints:486,grandsPrix:191,dnfs:27,championships:0,season:{position:17,points:3,grandPrixPoints:3,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:0}},
  'oliver-bearman': {wins:0,podiums:0,poles:0,careerPoints:66,grandsPrix:38,dnfs:6,championships:0,season:{position:13,points:18,grandPrixPoints:17,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:3}},
  'nico-hulkenberg': {wins:0,podiums:1,poles:1,careerPoints:624,grandsPrix:260,dnfs:50,championships:0,season:{position:18,points:2,grandPrixPoints:2,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:3}},
  'gabriel-bortoleto': {wins:0,podiums:0,poles:0,careerPoints:29,grandsPrix:34,dnfs:6,championships:0,season:{position:14,points:10,grandPrixPoints:10,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:0}},
  'carlos-sainz': {wins:4,podiums:29,poles:6,careerPoints:1342.5,grandsPrix:240,dnfs:45,championships:0,season:{position:15,points:6,grandPrixPoints:6,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:2}},
  'alexander-albon': {wins:0,podiums:2,poles:0,careerPoints:318,grandsPrix:138,dnfs:25,championships:0,season:{position:16,points:5,grandPrixPoints:5,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:2}},
  'fernando-alonso': {wins:32,podiums:106,poles:22,careerPoints:2394,grandsPrix:438,dnfs:92,championships:2,season:{position:19,points:1,grandPrixPoints:1,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:4}},
  'lance-stroll': {wins:0,podiums:3,poles:1,careerPoints:325,grandsPrix:200,dnfs:40,championships:0,season:{position:20,points:0,grandPrixPoints:0,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:6}},
  'sergio-perez': {wins:6,podiums:39,poles:3,careerPoints:1638,grandsPrix:292,dnfs:46,championships:0,season:{position:22,points:0,grandPrixPoints:0,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:4}},
  'valtteri-bottas': {wins:10,podiums:67,poles:20,careerPoints:1797,grandsPrix:257,dnfs:34,championships:0,season:{position:21,points:0,grandPrixPoints:0,wins:0,podiums:0,poles:0,fastestLaps:0,dnfs:5}}
}

const driverRows = getContent('drivers')
for (const d of driverRows) {
  const v = verified[d.id]
  if (!v) continue
  putContent('drivers', d.id, {...d, ...v, career:{grandsPrix:v.grandsPrix,points:v.careerPoints,wins:v.wins,podiums:v.podiums,poles:v.poles,championships:v.championships,dnfs:v.dnfs}, season:v.season, statsUpdatedAt:'2026-08-18', statsSource:'Initial seed; refreshable from Jolpica F1 public data'})
}

// Initial constructor points seed; later refreshes use public F1 result data.
const teamPoints = {Mercedes:379,Ferrari:307,McLaren:220,'Red Bull Racing':177,'Racing Bulls':66,Alpine:61,'Haas F1 Team':21,Audi:12,Williams:11,'Aston Martin':1,Cadillac:0}
const teams = getContent('teams')
for (const t of teams) {
  const pts = teamPoints[t.name]
  if (pts == null) continue
  putContent('teams', t.id || t.name, {...t, points2026:pts, seasonPoints:pts, statsUpdatedAt:'2026-08-18', statsSource:'Initial seed; refreshable from Jolpica F1 public data'})
}

// Current 2026 calendar seed used by the local database.
const CURRENT_CIRCUITS = [
['Australia','🇦🇺','Albert Park','Melbourne','2026-03-08',5.278,58,306.124,16,false],['China','🇨🇳','Shanghai International','Shanghai','2026-03-15',5.451,56,305.066,16,true],['Japan','🇯🇵','Suzuka','Suzuka','2026-03-29',5.807,53,307.471,18,false],['Miami','🇺🇸','Miami International Autodrome','Miami Gardens','2026-05-03',5.412,57,308.326,19,true],['Canada','🇨🇦','Circuit Gilles-Villeneuve','Montreal','2026-05-24',4.361,70,305.27,14,true],['Monaco','🇲🇨','Circuit de Monaco','Monte Carlo','2026-06-07',3.337,78,260.286,19,false],['Spain','🇪🇸','Barcelona-Catalunya','Montmeló','2026-06-14',4.657,66,307.236,14,false],['Austria','🇦🇹','Red Bull Ring','Spielberg','2026-06-28',4.326,71,307.146,10,false],['Great Britain','🇬🇧','Silverstone','Silverstone','2026-07-05',5.891,52,306.198,18,true],['Belgium','🇧🇪','Spa-Francorchamps','Stavelot','2026-07-19',7.004,44,308.052,19,false],['Hungary','🇭🇺','Hungaroring','Mogyoród','2026-07-26',4.381,70,306.63,14,false],['Netherlands','🇳🇱','Zandvoort','Zandvoort','2026-08-23',4.259,72,306.587,14,true],['Italy','🇮🇹','Monza','Monza','2026-09-06',5.793,53,306.72,11,false],['Spain','🇪🇸','Madrid IFEMA','Madrid','2026-09-13',5.474,55,301.07,20,false],['Azerbaijan','🇦🇿','Baku City Circuit','Baku','2026-09-26',6.003,51,306.049,20,false],['Malaysia','🇲🇾','Sepang International Circuit','Kuala Lumpur','2026-10-04',5.543,56,310.408,15,false],['Singapore','🇸🇬','Marina Bay Street Circuit','Singapore','2026-10-11',4.94,62,306.143,19,true],['United States','🇺🇸','Circuit of The Americas','Austin','2026-10-25',5.513,56,308.405,20,false],['Mexico','🇲🇽','Autódromo Hermanos Rodríguez','Mexico City','2026-11-01',4.304,71,305.354,17,false],['Brazil','🇧🇷','Interlagos','São Paulo','2026-11-08',4.309,71,305.879,15,false],['Las Vegas','🇺🇸','Las Vegas Strip Circuit','Las Vegas','2026-11-21',6.201,50,309.958,17,false],['Qatar','🇶🇦','Lusail International Circuit','Lusail','2026-11-29',5.419,57,308.611,16,false],['Abu Dhabi','🇦🇪','Yas Marina Circuit','Abu Dhabi','2026-12-06',5.281,58,306.183,16,false]
]
const CIRCUIT_META = {
  1:{openedYear:1996,firstGrandPrix:1996,famousCorners:"Turns 3, 9–10 and Turn 12",description:"Albert Park is a fast temporary circuit built around Melbourne’s park roads. Long straights and heavy braking zones are mixed with flowing sections.",fastestLapTime:"1:19.813",fastestLapDriver:"Charles Leclerc",fastestLapYear:2024},
  2:{openedYear:2004,firstGrandPrix:2004,famousCorners:"Turns 1–2 and Turn 13 hairpin",description:"Shanghai combines a long back straight with a tightening first sector that places high demands on front-tyre management.",fastestLapTime:"1:32.238",fastestLapDriver:"Michael Schumacher",fastestLapYear:2004},
  3:{openedYear:1962,firstGrandPrix:1987,famousCorners:"130R, Spoon Curve and the Esses",description:"Suzuka is Honda’s famous figure-of-eight circuit. Its fast Esses, Degners, Spoon and 130R reward precision and commitment.",fastestLapTime:"1:30.965",fastestLapDriver:"Kimi Antonelli",fastestLapYear:2025},
  4:{openedYear:2022,firstGrandPrix:2022,famousCorners:"Turns 6–8 and the long back straight",description:"Miami combines a temporary street-circuit feel with long straights and a technical triple-apex section.",fastestLapTime:"1:29.708",fastestLapDriver:"Max Verstappen",fastestLapYear:2023},
  5:{openedYear:1978,firstGrandPrix:1978,famousCorners:"Senna S, Hairpin and Wall of Champions",description:"Circuit Gilles-Villeneuve is a low-downforce island circuit defined by heavy braking, kerbs and short bursts of acceleration.",fastestLapTime:"1:13.078",fastestLapDriver:"Valtteri Bottas",fastestLapYear:2019},
  6:{openedYear:1929,firstGrandPrix:1950,famousCorners:"Casino, Hairpin, Swimming Pool and Rascasse",description:"Monaco is the ultimate precision circuit. Its narrow streets leave almost no margin for error.",fastestLapTime:"1:12.909",fastestLapDriver:"Lewis Hamilton",fastestLapYear:2021},
  7:{openedYear:1991,firstGrandPrix:1991,famousCorners:"Turn 3, La Caixa and Campsa",description:"Barcelona-Catalunya is a benchmark circuit with a broad mix of corner speeds that exposes aerodynamic balance and tyre management.",fastestLapTime:"1:16.330",fastestLapDriver:"Max Verstappen",fastestLapYear:2021},
  8:{openedYear:1969,firstGrandPrix:1970,famousCorners:"Remus and uphill Turn 3",description:"The Red Bull Ring is short but intense, with three major acceleration-and-braking complexes linked by fast sections.",fastestLapTime:"1:07.924",fastestLapDriver:"Oscar Piastri",fastestLapYear:2025},
  9:{openedYear:1947,firstGrandPrix:1950,famousCorners:"Copse, Maggotts–Becketts and Stowe",description:"Silverstone grew from an RAF airfield into one of F1’s most famous high-speed circuits.",fastestLapTime:"1:27.097",fastestLapDriver:"Max Verstappen",fastestLapYear:2020},
  10:{openedYear:1921,firstGrandPrix:1950,famousCorners:"Eau Rouge–Raidillon, Pouhon and Blanchimont",description:"Spa runs through the Ardennes and remains the longest current F1 circuit.",fastestLapTime:"1:44.701",fastestLapDriver:"Sergio Perez",fastestLapYear:2024},
  11:{openedYear:1986,firstGrandPrix:1986,famousCorners:"Turn 1, Turn 4 and the final sector",description:"The Hungaroring is tight and technical, with relatively few long straights and a karting-style rhythm.",fastestLapTime:"1:16.627",fastestLapDriver:"Lewis Hamilton",fastestLapYear:2020},
  12:{openedYear:1948,firstGrandPrix:1952,famousCorners:"Tarzan, Hugenholtzbocht and Arie Luyendijkbocht",description:"Zandvoort winds through the dunes beside the North Sea. Banking and elevation changes define its character.",fastestLapTime:"1:11.097",fastestLapDriver:"Lewis Hamilton",fastestLapYear:2021},
  13:{openedYear:1922,firstGrandPrix:1950,famousCorners:"Rettifilo, Lesmo, Ascari and Parabolica",description:"Monza is the Temple of Speed. Low drag and efficient power delivery are crucial.",fastestLapTime:"1:20.901",fastestLapDriver:"Lando Norris",fastestLapYear:2025},
  14:{openedYear:2026,firstGrandPrix:2026,famousCorners:"Technical middle sector and high-speed final loop",description:"Madrid’s new F1 venue combines a permanent technical section with a faster urban-style section around IFEMA.",fastestLapTime:null,fastestLapDriver:null,fastestLapYear:null},
  15:{openedYear:2016,firstGrandPrix:2016,famousCorners:"Turn 8 castle section and the long start-finish straight",description:"Baku contrasts a slow historic section with one of F1’s longest full-throttle runs.",fastestLapTime:"1:43.009",fastestLapDriver:"Charles Leclerc",fastestLapYear:2019},
  16:{openedYear:1999,firstGrandPrix:1999,famousCorners:"Turns 1–2 and the final hairpin",description:"Sepang is a wide Hermann Tilke circuit built for racing in Malaysia’s heat and humidity.",fastestLapTime:"1:34.080",fastestLapDriver:"Juan Pablo Montoya",fastestLapYear:2004},
  17:{openedYear:2008,firstGrandPrix:2008,famousCorners:"Memorial, Anderson Bridge and final chicane",description:"Marina Bay was F1’s first night race and combines heavy braking with a bumpy street surface.",fastestLapTime:"1:33.808",fastestLapDriver:"Lewis Hamilton",fastestLapYear:2025},
  18:{openedYear:2012,firstGrandPrix:2012,famousCorners:"Turn 1, the Esses and downhill hairpin",description:"COTA combines a dramatic uphill first corner with fast direction changes inspired by famous European circuits.",fastestLapTime:"1:36.169",fastestLapDriver:"Charles Leclerc",fastestLapYear:2019},
  19:{openedYear:1959,firstGrandPrix:1963,famousCorners:"Peraltada and Foro Sol",description:"Mexico City’s high altitude reduces air density and complicates cooling and aerodynamic efficiency.",fastestLapTime:"1:17.774",fastestLapDriver:"Valtteri Bottas",fastestLapYear:2021},
  20:{openedYear:1938,firstGrandPrix:1973,famousCorners:"Senna S, Ferradura and Juncao",description:"Interlagos is compact and undulating, with a long uphill run and a demanding anti-clockwise layout.",fastestLapTime:"1:10.540",fastestLapDriver:"Valtteri Bottas",fastestLapYear:2018},
  21:{openedYear:2023,firstGrandPrix:2023,famousCorners:"The Strip straight and Turn 5 hairpin",description:"The modern Las Vegas Strip Circuit is a fast night-time street track where long straights make low drag valuable.",fastestLapTime:"1:33.365",fastestLapDriver:"Max Verstappen",fastestLapYear:2025},
  22:{openedYear:2004,firstGrandPrix:2021,famousCorners:"Fast flowing middle and final sectors",description:"Lusail was originally built for motorcycle racing and features a fast, flowing rhythm.",fastestLapTime:"1:22.384",fastestLapDriver:"Lando Norris",fastestLapYear:2024},
  23:{openedYear:2009,firstGrandPrix:2009,famousCorners:"Turn 5 and the final technical sector",description:"Yas Marina balances long straights and heavy braking with a technical final sector.",fastestLapTime:"1:25.637",fastestLapDriver:"Kevin Magnussen",fastestLapYear:2024},
}
const currentCircuitRows=getContent('circuits')
CURRENT_CIRCUITS.forEach((x,i)=>{const [country,flag,name,city,date,length,laps,distance,turns,sprint]=x;const meta=CIRCUIT_META[i+1]||{};const id=String(i+1);const existing=currentCircuitRows.find(c=>String(c.id)===id);const value={id,round:i+1,country,flag,name,city,date,length,laps,distance,turns,sprint,eventName:name==='Sepang International Circuit'?'Gulf Air Bahrain Grand Prix in Malaysia':`${country} Grand Prix`,officialSlug:name==='Sepang International Circuit'?'bahrain':undefined,...meta,records:existing?.records||{}};if(!existing||!existing.layoutSvg||!existing.description)putContent('circuits',id,{...(existing||{}),...value})})


// Add beginner-oriented circuit context without replacing the core circuit facts.
for (const c of getContent('circuits')) {
  putContent('circuits',c.id,{...c,historyNote:c.historyNote||`The circuit opened in ${c.openedYear||'the recorded year'} and hosted its first Formula 1 Grand Prix in ${c.firstGrandPrix||'the recorded season'}.`,trackGuide:c.trackGuide||`${c.description||'This circuit combines a distinctive sequence of corners and straights.'} The layout contains ${c.turns||'several'} turns over ${c.length||'the recorded'} km.`,racingFocus:c.racingFocus||`Drivers balance braking, corner entry, tyre management and straight-line efficiency around ${c.famousCorners||'the key corners of the circuit'}.`,beginnerTip:c.beginnerTip||`For a first viewing, watch the main braking zones and then compare how different drivers use the same corners.`})
}

// Driver standings after the completed Hungarian GP (Round 11), with the Dutch GP next.
const CURRENT_POINTS = {'george-russell':154,'kimi-antonelli':219,'charles-leclerc':144,'lewis-hamilton':159,'lando-norris':128,'oscar-piastri':92,'max-verstappen':109,'isack-hadjar':68,'liam-lawson':40,'arvid-lindblad':23,'pierre-gasly':41,'franco-colapinto':1,'esteban-ocon':3,'oliver-bearman':18,'nico-hulkenberg':2,'gabriel-bortoleto':10,'carlos-sainz':6,'alexander-albon':5,'fernando-alonso':1,'lance-stroll':0,'sergio-perez':0,'valtteri-bottas':0}
const CURRENT_POSITIONS = {'kimi-antonelli':1,'lewis-hamilton':2,'george-russell':3,'charles-leclerc':4,'lando-norris':5,'max-verstappen':6,'oscar-piastri':7,'isack-hadjar':8,'liam-lawson':9,'pierre-gasly':10,'arvid-lindblad':11,'franco-colapinto':12,'oliver-bearman':13,'gabriel-bortoleto':14,'carlos-sainz':15,'alexander-albon':16,'esteban-ocon':17,'nico-hulkenberg':18,'fernando-alonso':19,'lance-stroll':20,'valtteri-bottas':21,'sergio-perez':22}
for (const d of getContent('drivers')) putContent('drivers',d.id,{...d,season:{...d.season,points:CURRENT_POINTS[d.id]??d.season?.points,position:CURRENT_POSITIONS[d.id]??d.season?.position},statsUpdatedAt:'2026-08-18'})
const sums={};for(const d of getContent('drivers'))sums[d.team]=(sums[d.team]||0)+Number(d.season?.points||0)
for(const t of getContent('teams'))putContent('teams',t.id||t.name,{...t,seasonPoints:sums[t.name]||0,points2026:sums[t.name]||0,statsUpdatedAt:'2026-08-18'})

console.log('Database seeded:', process.env.F1_DB_PATH || path.join(__dirname,'f1-grid.sqlite'))

// v4.3 tyre education enrichment. These values are stored in SQLite and can be edited in Admin.
const TYRE_V43 = [
  {id:'c1',mark:'WHITE',name:'C1 • Hardest',compound:'C1',color:'#f6f6f7',grip:'Maximum durability • lowest peak grip',detail:'The hardest 2026 slick compound. Designed for the most demanding circuits where heat and energy loads are high.',use:'Long race stints / high degradation',estimatedLaps:'~25–40+ laps*',explanation:'C1 is the hardest slick in the 2026 range and is built for durability and high-energy circuits.',conditions:'High tyre load, heat or abrasive asphalt.',driverFeel:'Stable and durable, but usually less peak grip and slower warm-up than softer compounds.',example:'A team may choose C1 when preserving tyre life is more valuable than maximum one-lap grip.',strategyNote:'Life varies substantially by circuit, setup, temperature and degradation.'},
  {id:'c2',mark:'WHITE',name:'C2 • Hard',compound:'C2',color:'#f6f6f7',grip:'Durability with more pace than C1',detail:'A durable slick compound suited to fast, hot or abrasive circuits and conservative race strategies.',use:'Long stints / high-energy circuits',estimatedLaps:'~20–35 laps*',explanation:'C2 sits between C1 and C3 and is designed to provide a strong durability-to-performance compromise.',conditions:'Fast circuits, higher loads or races where tyre life is important.',driverFeel:'More responsive than C1 while retaining strong durability.',example:'A team may use C2 for a long first stint before switching to a faster compound.',strategyNote:'Actual stint length depends on degradation and race conditions.'},
  {id:'c3',mark:'YELLOW',name:'C3 • Medium-range',compound:'C3',color:'#ffd600',grip:'Balanced performance and durability',detail:'The versatile middle compound of the 2026 range. It can be the hard, medium or soft tyre in a weekend nomination.',use:'Flexible race strategy',estimatedLaps:'~15–30 laps*',explanation:'C3 is the most versatile compound in the 2026 range and can fill different roles depending on the three-compound selection.',conditions:'A wide variety of circuits and conditions.',driverFeel:'A balanced response between grip and durability.',example:'C3 can be the middle tyre at one race and the softest selected tyre at another.',strategyNote:'Its strategic value comes from its flexibility rather than one fixed lap life.'},
  {id:'c4',mark:'RED',name:'C4 • Soft',compound:'C4',color:'#e10600',grip:'Fast warm-up • high grip',detail:'A softer slick designed to reach performance quickly and provide strong peak grip on lower-severity circuits.',use:'Qualifying / short-to-medium stints',estimatedLaps:'~10–25 laps*',explanation:'C4 is a soft compound that prioritises warm-up and peak performance while accepting greater degradation than C1–C3.',conditions:'Lower-severity circuits, cooler conditions or when immediate grip is valuable.',driverFeel:'Responsive and grippy when inside its operating window.',example:'C4 can be valuable for a qualifying-style run or an aggressive short race stint.',strategyNote:'A soft compound can lose performance quickly if degradation is high.'},
  {id:'c5',mark:'RED',name:'C5 • Softest',compound:'C5',color:'#e10600',grip:'Maximum peak grip • shortest life',detail:'The softest 2026 slick compound, intended for circuits where maximum mechanical grip is needed and tyre loads are relatively low.',use:'Qualifying / short aggressive stints',estimatedLaps:'~8–20 laps*',explanation:'C5 is the softest slick in the 2026 range and is designed for maximum grip rather than maximum durability.',conditions:'Street circuits, smooth asphalt and low-severity layouts.',driverFeel:'Very responsive and high-grip, but more sensitive to overheating and degradation.',example:'A new C5 can be used to maximise a final qualifying lap.',strategyNote:'The fastest compound for one lap is not automatically the best race compound.'},
  {id:'intermediate',mark:'GREEN',name:'Intermediate',compound:'Wet-weather',color:'#13c47a',grip:'Damp / changing conditions',detail:'The green intermediate tyre is designed for a wet track without substantial standing water and for crossover conditions between slicks and full wets.',use:'Light rain / damp / drying track',estimatedLaps:'Highly condition-dependent*',explanation:'Intermediates provide a broad crossover window and can work on a wet surface without standing water or on a drying circuit.',conditions:'Light rain, damp track or a drying surface.',driverFeel:'More water displacement and confidence than a slick, while remaining faster than a full wet when conditions allow.',example:'When rain begins and slicks can no longer maintain grip, the team may switch to intermediates.',strategyNote:'The crossover decision is one of the most important tyre calls in changing weather.'},
  {id:'wet',mark:'BLUE',name:'Full Wet',compound:'Wet-weather',color:'#1d8cff',grip:'Heavy rain / standing water',detail:'The blue full wet tyre is designed to displace substantially more water and improve resistance to aquaplaning in very wet conditions.',use:'Heavy rain / standing water',estimatedLaps:'Highly condition-dependent*',explanation:'Full wets are the most capable tyre for heavy rain and standing water, although visibility can still make conditions unsafe.',conditions:'Heavy rain and significant standing water.',driverFeel:'Greater water displacement but substantially lower dry-track performance.',example:'A full wet becomes relevant when the circuit is too wet for an intermediate to work effectively.',strategyNote:'Even the full wet cannot make a dangerously flooded or low-visibility circuit safe.'}
]
for (const tyre of TYRE_V43) {
  const existing = getContentById('tyres', tyre.id) || {}
  putContent('tyres', tyre.id, {...existing, ...tyre})
}
for (const legacyTyreId of ['hard','medium','soft']) deleteContent('tyres', legacyTyreId)
